version: '3.8'

services:
  frontend:
    container_name: rural-producers-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://host.docker.internal:3000}
    volumes:
      - .:/app
      - /app/node_modules
      - pnpm-store:/root/.local/share/pnpm/store
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${VITE_API_URL:-http://host.docker.internal:3000}
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
    stdin_open: true

networks:
  app-network:
    driver: bridge

volumes:
  pnpm-store: